#!/bin/bash
read -p "Do you agree to the Minecraft EULA? (https://account.mojang.com/documents/minecraft_eula) [y/n] " eula
if [ "$eula" = "y" ]; then
    echo "proceeding..."
elif [ "$eula" = "n" ]; then
    echo "cancelling..."
    exit N >/dev/null 2>&1
elif [ "$eula" = "" ]; then
    echo "cancelling..."
    exit N >/dev/null 2>&1
else
    echo "cancelling..."
    exit N >/dev/null 2>&1
fi
if [[ $(which java) ]]; then
    echo "Java is already installed"
else
    echo "Downloading Java..."
    sudo apt-get install default-jre
fi
if [[ $(which wget) ]]; then
    echo "wget is alerady installed"
    echo ""
else
    echo "Downloading wget..."
    sudo apt-get install wget
fi
read -p "Do you want to run the server with a GUI? [y/n] " gui
wget -q --show-progress https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar 	# Downloads the server software from mojang
java -Xmx2G -Xms2G -jar server.jar nogui >/dev/null 2>&1 								# Runs the server once to get additional files
sed -i -e 's/false/true/g' eula.txt 											# replaces false with true in the eula
touch server														# creates bash script file
if [ "$gui" = "y" ]; then
    echo "java -Xmx2G -Xms2G -jar server.jar" >> server 								# writes the server startup command with the gui to the second bash script
elif [ "$gui" = "n" ]; then
    echo "java -Xmx2G -Xms2G -jar server.jar nogui" >> server								# writes the server startup command without the gui to the second bash script
else
    echo "Unknown input. Running the server without the gui"
    echo "java -Xmx2G -Xms2G -jar server.jar nogui" >> server								# if the input is unknown the server will be run without the gui
fi
chmod +x server 													# makes the second bash script executable
echo "To change the default settings of the Minecraft Server you'll need to edit server.properties"
